### ISSUE TITLE
Performance of `ServiceResources` in request handling

### ISSUE THREAD

**Issue by sosthene-nitrokey** [trussed-dev/trussed#136]
When an app has backends configured that deal with `core` requests, they will "see" each core API request.

But most backends get all the "resources" from `ServiceResources`, but loading the keystore necessitates forking the RNG (because the keystore needs an RNG for `KeyId` generation. The same is true for  the `cerstore` and the `counterstore`.

However many requests will never touch any of these stores and those that do will probably only ever touch one.

Since generating RNG is expensive (on embedded harware), if each intermediary backend that sees the requests forks the RNG that way it might add up to a significant overhead.
For example in opcard, which has the RSA backend enabled, each requests to the core API ends up forking the RNG at least 5 times:

- https://github.com/Nitrokey/trussed-rsa-backend/blob/main/src/lib.rs#L441
- https://github.com/Nitrokey/trussed-rsa-backend/blob/main/src/lib.rs#L442
- https://github.com/trussed-dev/trussed/blob/main/src/service.rs#L144
- https://github.com/trussed-dev/trussed/blob/main/src/service.rs#L145
- https://github.com/trussed-dev/trussed/blob/main/src/service.rs#L146

And then [some requests](https://github.com/trussed-dev/trussed/blob/main/src/service.rs#L146) fork it once more through `self.rng`.

This seems unnecessary and could be one of the reason of the slowness of opcard.

I see two way to reduce the number of forking of the RNG:

- Avoid using `self.rng()` (I'm guilty of this in backends) and instead use the already-forked RNG from the `keystore` [like the crypto mechanisms do](https://github.com/trussed-dev/trussed/blob/main/src/mechanisms/x255.rs#L89)
- Use lazily intialize the `keystore`, `certstore` and `counterstore` only for requests that need it.

Ideally we could also totally avoid forking the RNG for requests that only need to read data from the keystore and don't need to generate `KeyId`s.

**Comment by sosthene-nitrokey** [comment]
We could also store the stores initialized stores in the `ClientContext`, including the forked RNG. This would also make the accessible to other backends without having to copy the path again.

**Comment by robin-nitrokey** [comment]
> Use lazily intialize the keystore, certstore and counterstore only for requests that need it.

Generally, I’m not a big fan of the huge `reply_to` function.  It also introduces a significant stack burden.  I would split it into one function per (non-trivial) API call.  Then we could also move the store instantiation to those functions that really need it.

> This would also make the accessible to other backends without having to copy the path again.

Do we even need owned stores?  Couldn’t we just use references?

**Comment by robin-nitrokey** [comment]
> I don't understand why that is the case. Should the compiler be able to reuse the same stack space across incompatible branches?

You would think so, but apparently it is not the case.  On the lpc55, the stack size is ca. 20 kB.

> I am not sure what you mean by that. The stores are already &mut everywhere in trussed.

I mean to replace `ClientKeystore { path: PathBuf }` with `ClientKeystore<'a> { path: &'a Path }`, in case you worry about the path copies.

**Comment by sosthene-nitrokey** [comment]
I believe that would work, but I'm not sure it's the most costly part.

It would also be incompatible with the idea to store them in the ClientContex.
