### ISSUE TITLE
Dangerous `unsafe` in `impl_reply`

### ISSUE THREAD

**Issue by sosthene-nitrokey** [trussed-dev/trussed#84]
https://github.com/trussed-dev/trussed/blob/main/src/api/macros.rs#L96

```rust
    impl From<Reply> for $reply {
        fn from(reply: Reply) -> reply::$reply {
            match reply {
                Reply::$reply(reply) => reply,
                _ => { unsafe { unreachable_unchecked() } }
            }
        }
    }
```

This `unsafe` is not sound and this impl is part of the public API. I think we could replace it with a `panic!`, since it is only used by [`PollClient::request`](https://docs.rs/trussed/latest/trussed/client/trait.PollClient.html#tymethod.request). To reduce the risk of panicking I would instead use `TryFrom`.

**Comment by robin-nitrokey** [comment]
Yeah, this should really be a `TryFrom`.  If we make changes to the request and reply types, it could make sense to have a trait that defines the request and reply types for a syscall.

**Comment by robin-nitrokey** [comment]
I’ll prepare a PR.  Will also be useful for API extensions too because I’m using `TryFrom` there, so I had to duplicate `FutureResult`.

**Comment by sosthene-nitrokey** [comment]
I'm making a PR that adds a trait that does bindings between the request and reply types.
